---
# tasks file for common
- vars:
    pack: [ 'vim', 'tree', 'tmux', 'mtr', 'vivaldi' ]
    kvm_list: [ 'qemu', 'qemu-kvm', 'libvirt-daemon', 'libvirt-client', 'bridge-utils', 'virt-manager']

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pack }}"

- name: Install KVM
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ kvm_list }}"

